checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12

            tests:
                override:
                    - php-scrutinizer-run

        rebuild-0:
            environment:
                php: 7.4.12

                variables:
                    REBUILD: 0

            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --debug --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover

        rebuild-1:
            environment:
                php: 7.4.12

                variables:
                    REBUILD: 1

            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --debug --coverage-clover ./coverage.xml"
                        on_node: 2
                        coverage:
                            file: coverage.xml
                            format: php-clover
